version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START BUILD'
    - run: go get -v -t -d ./...
    - run: go test -v ./...
    - run: go build -o addUser ./cmd/batch/user/addUser.go
    - run: echo 'END BUILD'
    - save_cache:
        key: addUser
        paths:
        - /go/src/github.com/yusukemisa/registMember/addUser

  cmd:
    docker:
    - image: google/cloud-sdk
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - restore_cache:
        key: addUser
    - run:
        name: Exec command
        environment:
          ProjectID: my-book-shelf-50355
          GCP_CREDENTIALS: /etc/google/application-credentials.json
        command: |
          mkdir -p /etc/google
          echo ${GCP_CREDENTIALS_JSON} | base64 --decode > ${GCP_CREDENTIALS}
          gcloud auth activate-service-account --key-file=${GCP_CREDENTIALS} --project ${ProjectID}
          chmod 755 ./addUser | ./addUser
          echo 'END CMD'

workflows:
  version: 2
  commit:
    jobs:
    - build
  scheduled_job:
    jobs:
    - build
    - cmd
    triggers:
    - schedule:
        cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
        filters:
          branches:
            only:
            - master