version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START CMD'
    - run: go get -v -t -d ./...
    - run: go run -v cmd/batch/user/addUser.go
    - run: echo 'END CMD'

  cmd:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START CMD'
    - run: go get -v -t -d ./...
    - run:
        name: Set environment variables
        environment:
          ProjectID: my-book-shelf-50355
        command: |
          echo ${GCP_CREDENTIALS_JSON} | base64 --decode > ${GCP_CREDENTIALS}
    - run: go run -v cmd/batch/user/addUser.go
    - run: echo 'END CMD'

workflows:
  version: 2
  commit:
    jobs:
    - build
  scheduled_job:
    jobs:
    - cmd
    triggers:
    - schedule:
        cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
        filters:
          branches:
            only:
            - master