version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START CMD'
    - run: go get -v -t -d ./...
    - run: go run -v cmd/batch/user/addUser.go
    - run: echo 'END CMD'

  cmd:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START CMD'
    - run: go get -v -t -d ./...
    - run: go run -v cmd/batch/user/addUser.go
    - run: echo 'END CMD'

workflows:
  version: 2
  build-workflow:
    jobs:
    - build
  cmd-exec:
    triggers:
    - schedule:
      cron: "0 0 * * *"
      filters:
        branches:
          only:
          - master
    jobs:
      - cmd
