version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START CMD'
    - run: go get -v -t -d ./...
    - run: go run -v cmd/batch/user/addUser.go
    - run: echo 'END CMD'

  cmd:
    docker:
    - image: circleci/golang:1.9
    working_directory: /go/src/github.com/yusukemisa/registMember
    steps:
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: echo 'START CMD'
    - run: go get -v -t -d ./...
    - run: go run -v cmd/batch/user/addUser.go
    - run: echo 'END CMD'

workflows:
  version: 2
  nightly:
    triggers:
    - schedule:
        cron: "*/3 * * * *"
        filters:
          branches:
            only:
            - master
            - beta
    jobs:
    - cmd
